---
name: Tie-CountLoop
version: 1.3
license: perl
distribution_type: module
requires:
  perl: 5.6.1
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Tie::CountLoop:
    file: lib/Tie/CountLoop.pm
    version: 1.3
generated_by: Module::Build version 0.20
