--- #YAML:1.0
name:                Tie-CountLoop
version:             1.7
abstract:            Tie::CountLoop Is a tie SCALAR with automatic increment/decrement untill a extramum value (with reset)
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
