---
name: Tie-CountLoop
version: 1.5
author:
  - DULAUNOY Fabrice <fabrice@dulaunoy.com
abstract: Have a counter looping in a scalar with min max and increment value.
license: perl
requires:
  perl: 5.6.1
provides:
  Tie::CountLoop:
    file: lib/Tie/CountLoop.pm
    version: 1.5
generated_by: Module::Build version 0.2611
